vision_assistant_path_config:
  camera_config_path: /home/pmlab/pm_Server/01_PM_Zelle/03_PM_DataBase/pm_assembly_database/Vision/vision_camera_configs/
  function_libary_path: "/home/pmlab/pm_ros2_ws/src/pm_vision_manager/pm_vision_manager/vision_functions/"
  process_library_path: /home/pmlab/pm_Server/01_PM_Zelle/03_PM_DataBase/pm_assembly_database/Vision/vision_processes/
  vision_database_path: /home/pmlab/pm_Server/01_PM_Zelle/03_PM_DataBase/pm_assembly_database/Vision/vision_image_db/
